# Generated by Django 5.2.9 on 2025-12-02 15:04

import portal.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv_copy',
            field=models.FileField(blank=True, null=True, upload_to='application_cvs/', validators=[portal.utils.validate_cv_file]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[portal.utils.validate_cv_file]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[portal.utils.validate_image_file]),
        ),
    ]
